### ISSUE TITLE
短期做一点科普文章吧

### ISSUE THREAD

**Issue by SmithGeorge** [my-new-home/new-home#3]
科普电脑知识

**Comment by pyyzcwg2833** [comment]
对的，不用太高深的技术，普及大众简单IT知识

**Comment by SmithGeorge** [comment]
那我行吗

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Euler Chen <notifications@github.com>
发送时间: Sunday, May 5, 2019 9:34:35 PM
收件人: my-new-home/new-home
抄送: Smith George; Author
主题: Re: [my-new-home/new-home] 短期做一点科普文章吧 (#3)


对的，不用太高深的技术，普及大众简单IT知识

―

**Comment by SmithGeorge** [comment]
想要试试看G

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Euler Chen <notifications@github.com>
发送时间: Sunday, May 5, 2019 9:34:35 PM
收件人: my-new-home/new-home
抄送: Smith George; Author
主题: Re: [my-new-home/new-home] 短期做一点科普文章吧 (#3)


对的，不用太高深的技术，普及大众简单IT知识

―

**Comment by pyyzcwg2833** [comment]
欢迎来当编辑，哈哈哈，进群讨论吧哈哈哈

**Comment by SmithGeorge** [comment]
在群啊,ic的群友

**Comment by SmithGeorge** [comment]
close掉喽
